


#--------- PATHS with modules to be used -------#
CNTJob PATHS SV 1
/home/pnovella/Physics/NEXT/sw/eGrassAna/algos

#--------- DATA -------#
CNTJob INPUT_DATA SV 7
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4213_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4218_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4219_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4220_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4221_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4222_*.root
/home/pnovella/Physics/NEXT/DATA/egrass/dst_new_Run4223_*.root

#--------- DATA READER -------#
CNTJob READER S gateReader

#--------- DATA WRITER -------#
CNTJob WRITER S gateWriter

#------ SAVE EVENTS IN OUTPUT FILE ----------# 
CNTJob SAVE I 0

#---------- NUMBER OF EVENTS TO ANALYZE ----------#
CNTJob NEVENTS I 500
CNTJob NDEBUG I 100

#---------- FIRST EVENS TO ANALYZE ----------#
CNTJob FEVENT I 0

#--------- ALGORITHMS -------#
CNTJob ALGOS SV 1
GrassChar

#------------- log file -------------#
CNTJob FLOG I 0
CNTJob FLOG S eGrassAna.log
#---------- histogram file ----------#
CNTJob FHISTOS S GrassChar_AutoTigger_NoHV.root
